### ISSUE TITLE
Cannot enable debug

### ISSUE THREAD

**Issue by djamps** [konikoni428/BM64_arduino#2]
Hi, If I uncomment debug in BM64_debug.h compiler reports many errors.   I'm trying to see the hex data going to and from the BM64, I'm hoping debug would show it.   Thanks for your help.

`BM64_Debug.h:10:25: error: '_swSerial' was not declared in this scope`

And so on...

**Comment by konikoni428** [comment]
Thank you for your report.
I found the bug and have updated the code and added an example.

Please check it out, as I do not have BM64 at the moment and cannot confirm that it works.
If you find any bugs, please leave a comment.

**Comment by djamps** [comment]
Thanks for the quick reply and sorry for my late reply.   I tested and it works now.   Thank you so much.
