### ISSUE TITLE
Cast warning

### ISSUE THREAD

**Issue by szymon-musial** [konikoni428/BM64_arduino#6]
`void BM64::sendCommand(uint8_t opCode, int link_index, uint8_t parameter)`
Creating array of type uint8_t via Implicit conversion generate warning shown below:
warning: narrowing conversion of 'link_index' from 'int' to 'uint8_t {aka unsigned char}' inside { } 
After explicit conversion warn gone

**Comment by konikoni428** [comment]
#7 merged.
Thank you for your contributing.
